# Generated by Django 5.1 on 2024-08-29 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.RemoveField(
            model_name='application',
            name='recruited',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Applications',
        ),
        migrations.CreateModel(
            name='recruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruited', models.BooleanField(default=False)),
                ('Applications', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='school_app.application')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='school_app.user')),
            ],
            options={
                'ordering': ['recruited'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='Applications',
            field=models.ManyToManyField(through='school_app.recruit', to='school_app.application'),
        ),
    ]
