# Generated by Django 5.1 on 2024-08-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Form',
        ),
        migrations.RenameModel(
            old_name='Application',
            new_name='Job',
        ),
        migrations.AlterModelOptions(
            name='recruit',
            options={},
        ),
        migrations.RenameField(
            model_name='recruit',
            old_name='user',
            new_name='Form',
        ),
        migrations.AddField(
            model_name='recruit',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
