# Generated by Django 5.1 on 2024-08-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_rename_user_form_rename_application_job_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruit',
            old_name='Applications',
            new_name='Job',
        ),
    ]
