# Generated by Django 5.1 on 2024-08-30 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_rename_applications_recruit_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='Applications',
        ),
        migrations.AddField(
            model_name='form',
            name='Job',
            field=models.ManyToManyField(through='school_app.Recruit', to='school_app.job'),
        ),
        migrations.AddField(
            model_name='recruit',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
