# Generated by Django 5.0 on 2024-09-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0010_remove_recruit_user_alter_form_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='declined',
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='recruited',
        ),
        migrations.AddField(
            model_name='recruit',
            name='status',
            field=models.CharField(blank=True, choices=[('recruited', 'Recruited'), ('declined', 'Declined')], default=None, max_length=10, null=True),
        ),
    ]
