# Generated by Django 5.0 on 2024-09-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0011_remove_recruit_declined_remove_recruit_recruited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='status',
        ),
        migrations.AddField(
            model_name='recruit',
            name='declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruit',
            name='recruited',
            field=models.BooleanField(default=False),
        ),
    ]
