# Generated by Django 5.2.7 on 2025-10-30 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0012_remove_recruit_status_recruit_declined_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='Job',
            new_name='jobs',
        ),
        migrations.RenameField(
            model_name='recruit',
            old_name='uploaded_on',
            new_name='applied_at',
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='Form',
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='Job',
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='declined',
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='recruited',
        ),
        migrations.AddField(
            model_name='recruit',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='form',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruit',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.form'),
        ),
        migrations.AddField(
            model_name='recruit',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.job'),
        ),
    ]
