# Generated by Django 5.2.7 on 2025-10-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0014_job_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='status',
        ),
    ]
