# Generated by Django 5.2.7 on 2025-10-30 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0015_remove_recruit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='jobs',
        ),
        migrations.AddField(
            model_name='form',
            name='jobs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.job'),
        ),
    ]
