# Generated by Django 5.2.7 on 2025-10-30 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0016_remove_form_jobs_form_jobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recruit',
            new_name='AppInfo',
        ),
    ]
