# Generated by Django 5.0.7 on 2024-08-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='ava.png', upload_to='avatars'),
        ),
    ]
